[package]
name = "zcash_params"
version = "0.1.0"
authors = ["Hanh <hanh425@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

serde = {version = "1.0.126", features = ["derive"]}

[build-dependencies]
hex = "0.4.3"
funty = "=1.1.0"
jubjub = "0.6.0"
byteorder = "^1.4"
group = "^0.9"
ff = "^0.9"
bls12_381 = "0.4.0"
rand = "0.8.4"
lazy_static = "1.4.0"

[dependencies.zcash_primitives]
git = "https://github.com/hhanh00/librustzcash.git"
rev = "f2d098abafd10e3744d23a28abe48ced19050f05"

[build-dependencies.zcash_primitives]
git = "https://github.com/hhanh00/librustzcash.git"
rev = "f2d098abafd10e3744d23a28abe48ced19050f05"
